# Base tools for a personal Mac. Review before installation.
# Homebrew installs dependencies automatically; do not list them here.

brew "bat"
brew "btop"
brew "coreutils"
brew "fd"
brew "fastfetch"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-filter-repo"
brew "gnupg"
brew "jless"
brew "jq"
brew "mosh"
brew "ripgrep"
brew "rsync"
brew "shellcheck"
brew "tig"
brew "tlrc"
brew "tmux"
brew "tree"
brew "uv"
brew "watchexec"
brew "wget"
brew "z"

cask "cursor"
cask "ghostty"
